<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>CollegeManagementWPF</RootNamespace>
    <AssemblyName>CollegeManagementWPF</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.3" />
    <PackageReference Include="WPF-UI" Version="3.0.5" />
    <PackageReference Include="MySql.Data" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\st_mary_logo.png" />
    <Resource Include="Assets\app.ico" />
    <Resource Include="Themes\Dark.xaml" />
    <Resource Include="Themes\Light.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Themes\Dark.xaml" />
    <Page Remove="Themes\Light.xaml" />
  </ItemGroup>

</Project>
